// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gahpfeizeoamompglrzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaHBmZWl6ZW9hbW9tcGdscnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA5NzQsImV4cCI6MjA2NTU0Njk3NH0.2F-p58ZohxxdaekYHfnO3i7vfR-zAEzeSiRzMEYzOvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);